#!/usr/bin/env bash

PROJECT="lexis-nexis-uni-downloader"

#@setup
#+Setup initial system dependencies and build docker image.
task-setup() {
    brew bundle
    task-build
}


#@build
#+Build docker image.
task-build() {
    docker build . -t $PROJECT
}

#@run
#+Run docker container.
task-run() {
    COOKIES=$HOME/Library/Application\ Support/Google/Chrome/Default/Cookies
    docker run -it \
        -e LN_URL="$LN_URL" \
        -e EZPROXY="$EZPROXY" \
        -e MACHINE_ID="$MACHINE_ID" \
        -e SESSION_ID="$SESSION_ID" \
        -v $(pwd):/app \
        -v "$COOKIES":"$COOKIES" \
        $PROJECT "$@"
}

#@get-cookies
#+Extract necessary cookies from Google Chrome.
task-get-cookies() {
    python3 -m venv .local-venv &&
    .local-venv/bin/pip install -q --upgrade pip &&
    .local-venv/bin/pip install -q browser_cookie3 &&
    .local-venv/bin/python scripts/get-cookies.py
}
